name: CI Workflow

on: [push, workflow_dispatch]

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1

      - name: AWS version
        run: |
          aws --version

      - name: Kubectl version
        run: kubectl version --client

      - name: Helm version
        run: helm version --short

      - name: Terraform version
        run: terraform version
        