name: CI Workflow

on: [push, workflow_dispatch]

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Check versions
        run: |
          asdf --version
          terraform --version
          aws --version
          kubectl version --client
          helm version --short